name: CI/CD MLflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || pip install mlflow pandas scikit-learn joblib matplotlib seaborn python-dotenv dagshub
      - name: Run mlflow project
        run: |
          mlflow run MLProject --env-manager=local
      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      - name: Commit and Push MLflow Artifacts
        run: |
          git config --global user.email "syaokifaradisa09@gmail.com"
          git config --global user.name "Muhammad Syaoki Faradisa"

          git add MLProject/artifact/ 
          git commit -m "CI: Add latest MLflow artifacts for run ${{ env.RUN_ID }}" || true
          git push

      - name: Build Docker Model
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "aids_prediction"
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Tag Docker Image
        run: |
          docker tag aids_prediction ${{ secrets.DOCKER_HUB_USERNAME }}/aids_prediction:latest
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/aids_prediction:latest
